### PR TITLE
refactor: refactor the repetitive  code

### PR DESCRIPTION
**Pull request by RohithChittibommala**
--> refactored the repetitive  code
-->  replaced the "var" keyword ES6 keywords
--> converted the class components to functional components

### CODE REVIEW

**Comment by AmanRaj1608** [comment]
Issue number?

**Comment by RohithChittibommala** [comment]
14On Sep 21, 2020 12:43 AM, Aman Raj <notifications@github.com> wrote:
Issue number?

**Comment by anujpuri72** [comment]
@RohithChittibommala  please point this to pr to the issue you want to refer

**Comment by RohithChittibommala** [comment]
@anujpuri72  sir 
#13

**Review by theyashshahs — APPROVED** [review]

**Pull request merged**
