### PR TITLE
navbar issue fixed

### PR DESCRIPTION
**Pull request by raghusodani**
@iiitv/project-maintainers

Please review my pull request referencing this issue #12

### CODE REVIEW

**Review by theyashshahs — COMMENTED** [review]
provide an ss of your work

**Comment by raghusodani** [comment]
Screenshot (114)

**Comment by raghusodani** [comment]
earlier "our club" drops down on mouse over and now it is dropping down on Click

**Review by anshumanv — CHANGES_REQUESTED** [review]
onMouseOver seems correct, please do some other enhancement

**Comment by raghusodani** [comment]
ok

**Pull request closed without merging**
